### ISSUE TITLE
[CI] Humble source build fails

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_controllers#898]
The humble source build on humble branch fails for some time now:
https://github.com/ros-controls/ros2_controllers/actions/workflows/humble-source-build.yml?query=branch%3Ahumble

But the scheduled one (tagged with branch=master) succeeds?

>    ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.powershell_command': cannot import name 'OVERRIDE_OPT' from 'em' (/usr/local/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/entry_point.py", line 120, in load_entry_points
      extension_type = load_entry_point(entry_point)
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/entry_point.py", line 168, in load_entry_point
      return entry_point.load()
    File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2465, in load
      return self.resolve()
    File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/local/lib/python3.10/dist-packages/colcon_powershell/shell/powershell.py", line 17, in <module>
      from colcon_core.shell.template import expand_template
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/shell/template/__init__.py", line 19, in <module>
      raise e from None
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/shell/template/__init__.py", line 10, in <module>
      from em import OVERRIDE_OPT
  ImportError: cannot import name 'OVERRIDE_OPT' from 'em' (/usr/local/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace

**Comment by christophfroehlich** [comment]
Seems to be fixed in the meantime
